# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a9d68c8eda979012ab670ae665c576dd6e4b029a3b043ef35a7d3dee02f369d9dc5fb3814b68fe0b8e635134354fdde43be93cae875dcad58f7e11def8f87084

test:
  secret_key_base: 7fcae57e955c786af6efe24124b6c34cd79f81a3ef3804b5f325e4db9cfa9874693578044494c0c6625dac21c75e54657ab01cef56b18dc1515027ba230eb563

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
